# Generated by Django 4.1.7 on 2023-03-22 04:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedRemoteNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('type', models.CharField(default='author', max_length=15)),
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id', models.URLField(blank=True, default=None)),
                ('url', models.URLField(blank=True, default=None)),
                ('host', models.URLField(default='https://social-distribution-media.herokuapp.com')),
                ('displayName', models.CharField(max_length=100)),
                ('github', models.URLField(blank=True)),
                ('profileImage', models.URLField(blank=True)),
                ('remote', models.BooleanField(default=False)),
                ('followers', models.ManyToManyField(blank=True, related_name='author_followers', to='api.author')),
                ('following', models.ManyToManyField(blank=True, related_name='author_following', to='api.author')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('id', models.URLField(blank=True, default=None)),
                ('title', models.TextField()),
                ('source', models.URLField(blank=True)),
                ('origin', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('contentType', models.TextField(choices=[('text/markdown', 'Common mark'), ('text/plain', 'UTF-8 plain text'), ('application/base64', 'Base 64 string'), ('image/png;base64', 'Base 64 string of PNG image'), ('image/jpeg;base64', 'Base 64 string of JPEG image')], default='text/plain')),
                ('content', models.TextField(blank=True)),
                ('categories', models.JSONField(blank=True, default=list)),
                ('count', models.IntegerField(default=0, editable=False)),
                ('comments', models.URLField(blank=True)),
                ('commentsSrc', models.JSONField(blank=True, default=dict)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('visibility', models.TextField(choices=[('PUBLIC', 'Public'), ('FRIENDS', 'Friends')], default='FRIENDS')),
                ('unlisted', models.BooleanField(default=False)),
                ('author', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.author')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('summary', models.TextField()),
                ('object', models.URLField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.author')),
            ],
        ),
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.author')),
                ('items', models.ManyToManyField(blank=True, to='api.post')),
            ],
            options={
                'verbose_name_plural': 'Inboxes',
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('summary', models.TextField()),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_request_from', to='api.author')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_request_to', to='api.author')),
            ],
            options={
                'verbose_name_plural': 'Follow Requests',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('_post_author_id', models.UUIDField(blank=True, null=True)),
                ('_post_id', models.UUIDField(blank=True, null=True)),
                ('id', models.URLField(blank=True, default=None)),
                ('comment', models.TextField()),
                ('contentType', models.TextField(choices=[('text/markdown', 'Common mark'), ('text/plain', 'UTF-8 plain text')])),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.author')),
            ],
        ),
    ]
